# Use the Node 18 Bullseye base image 
FROM node:18-bullseye

# Install Chromium and dependencies for e2e testing
# The '-o Acquire::Check-Valid-Until=false' flag is added to bypass the expired release file error
RUN apt-get -o Acquire::Check-Valid-Until=false update && apt-get install -y \
    chromium \
    libnss3 \
    libatk-bridge2.0-0 \
    libx11-xcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxi6 \
    libxtst6 \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json 
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your application code into the container
COPY . .

# Run your end-to-end tests
CMD ["npm", "run", "test:e2e"]
