name: Build and Release Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Package Extension
        run: |
          zip -r session-cookie-mixer.zip . -x "*.git*" -x ".github/*" -x "setup.sh" -x "build.sh" -x "Dockerfile" -x "docker-compose.yml"
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: session-cookie-mixer-artifact
          path: session-cookie-mixer.zip
